{% set name = "pypsa" %}
{% set version = "1.0.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypsa-{{ version }}.tar.gz
  sha256: 8425db249e269511895aaddd74acfdb9bfd47a6b943a5dcc1ce1287c3d84ef3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - levenshtein >=0.27.1
    - pydeck
    - plotly
    - shapely <2.1
    - seaborn
    - python >={{ python_min }}
    - highspy
    - numpy
    - scipy
    - pandas >=0.24
    - xarray <=2025.9.0
    - netcdf4
    - pytables
    - linopy >=0.5.5,<=0.5.7
    - matplotlib-base
    - geopandas >=0.9
    - networkx >=2
    - deprecation
    - validators

test:
  imports:
    - pypsa
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypsa.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python for Power Systems Analysis
  description: |
    PyPSA is a free software toolbox for simulating and optimising modern power
    systems that include features such as conventional generators with unit
    commitment, variable wind and solar generation, storage units, coupling to
    other energy sectors, and mixed alternating and direct current networks.
    PyPSA is designed to scale well with large networks and long time series.
  doc_url: https://pypsa.readthedocs.io
  dev_url: https://github.com/PyPSA/PyPSA

extra:
  recipe-maintainers:
    - lkstrp
    - coroa
    - nworbmot
    - fneum
