{% set name = "pypsa" %}
{% set version = "0.30.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypsa-{{ version }}.tar.gz
  sha256: bb14a933d4778fe616cf1ff27aebb57006c71e42648d477ecdd4d8285cf35924

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - pandas >=0.24
    - xarray
    - netcdf4
    - pytables
    - linopy >=0.3.12
    - matplotlib-base
    - geopandas >=0.9
    - networkx >=2
    - deprecation
    - validators

test:
  imports:
    - pypsa
  commands:
    - pip install highspy
    - pip check
  requires:
    - pip

about:
  home: https://pypsa.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python for Power Systems Analysis
  description: |
    PyPSA is a free software toolbox for simulating and optimising modern power
    systems that include features such as conventional generators with unit
    commitment, variable wind and solar generation, storage units, coupling to
    other energy sectors, and mixed alternating and direct current networks.
    PyPSA is designed to scale well with large networks and long time series.
  doc_url: https://pypsa.readthedocs.io
  dev_url: https://github.com/PyPSA/PyPSA

extra:
  recipe-maintainers:
    - lkstrp
    - coroa
    - nworbmot
    - fneum
